<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Medium</name>
   <tag></tag>
   <elementGuidId>5d5b95a3-59f0-45c1-beb0-52d19ccd50ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='password-strength-meter-label']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#password-strength-meter-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9309268f-0683-46ca-8b7c-69b0390c35b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>password-strength-meter-label</value>
      <webElementGuid>1baaea16-b80f-4c8f-b465-a802c01f97fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>password-strength-meter-label</value>
      <webElementGuid>0e4fe960-8cd2-4889-8d5b-2582e5626869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Medium</value>
      <webElementGuid>86f98e08-30dd-47d9-a7ce-84a3aa1a33b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;password-strength-meter-label&quot;)</value>
      <webElementGuid>d7bcfb6f-9132-4e05-a65e-9d098c06c741</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='password-strength-meter-label']</value>
      <webElementGuid>1ed93d01-f294-4b0c-9084-9e0eacb1be9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='password-strength-meter']/span</value>
      <webElementGuid>78efbe50-76d7-4f21-921f-d6e5d1716e36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::span[1]</value>
      <webElementGuid>2308fb97-fc9e-429b-803b-ca3ecf70befb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm Password'])[1]/preceding::span[1]</value>
      <webElementGuid>64429406-494a-4803-8c5f-8c0da4ebde60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create an Account'])[3]/preceding::span[2]</value>
      <webElementGuid>63c34802-5e12-4174-bf6f-ddf948a69252</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Medium']/parent::*</value>
      <webElementGuid>4b7bc2d2-7426-4e5b-9d35-5f391fd744fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/span</value>
      <webElementGuid>ef88d292-f23d-43de-9784-29ac6415db52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'password-strength-meter-label' and (text() = 'Medium' or . = 'Medium')]</value>
      <webElementGuid>d2fb3eee-ff3f-47c9-9287-fe7c94985ffb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
