<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>subscription checkbox</name>
   <tag></tag>
   <elementGuidId>5683ae6a-48df-43c2-8631-a0d3f5002456</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#is_subscribed</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='is_subscribed']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>97b44079-ebe7-44c3-9751-29de699138d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f83b285a-5cb6-4e5d-89fb-c7e80b38a8ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>is_subscribed</value>
      <webElementGuid>0b59e97f-c536-4800-b5db-71a5613a4876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sign Up for Newsletter</value>
      <webElementGuid>d5ae2383-1b7a-401e-914a-7217d3b1c1c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>87a13be9-5835-4683-a09d-5535f5edc1d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>is_subscribed</value>
      <webElementGuid>c3bba9ee-1969-4a5f-b57d-4d6e4969c9ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>9155fddf-696c-4d58-9dd5-66609ee55043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;is_subscribed&quot;)</value>
      <webElementGuid>37789d9f-9f48-4333-bc3b-26c2af54f22a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='is_subscribed']</value>
      <webElementGuid>84ad63f2-b990-4982-ba12-edc5cddac681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-validate']/fieldset/div[3]/input</value>
      <webElementGuid>1c934dbe-d3b7-45c4-8b71-bc9ac2ce4916</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>561cba23-b9d6-4c1a-aa66-499426563fba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'is_subscribed' and @title = 'Sign Up for Newsletter' and @id = 'is_subscribed']</value>
      <webElementGuid>b58d8a4a-89fa-492d-9d91-1bb4d1f2c549</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
